services:
  postgres:
    container_name: mydb
    image: postgres:latest
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    restart: unless-stopped      
    ports:
      - "5432:5432"
    networks:
      - default      
    volumes:      
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf

  api:
    image: workerapi
    build:
      context: .
      dockerfile: WorkerApi/Dockerfile
    depends_on:
      - mydb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5144
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_HTTP_PORTS=5144
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro      
    ports:
      - 5001:5001
      - 5144:5144